### ISSUE TITLE
Docker file have error : Cannot add PPA: 'ppa:~jonathonf/ubuntu/gcc-7.1'.

### ISSUE THREAD

**Issue by Timerunning** [feiyang-cai/iccps_aebs#1]
this command "RUN add-apt-repository ppa:jonathonf/gcc-7.1"
have an error
`Cannot add PPA: 'ppa:~jonathonf/ubuntu/gcc-7.1'.
The user named '~jonathonf' has no PPA named 'ubuntu/gcc-7.1'`
,how to fix it.

**Comment by feiyang-cai** [comment]
I have already update the docker file, and it works now.
